name: deploy-server

on:
  push:
    branches:
      - server
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read the current release number
        run: echo "RELEASE_NUMBER=$((${{ vars.RELEASE_NUMBER }} + 1))" >> $GITHUB_ENV

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/public_html 
            git pull origin server
