name: test-version

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read the current release number
        run: |
          release_number=$(cat ./release_number.txt)
          echo "Current Release Number: $release_number"
          echo "New Release Number: $((release_number + 1))" > release_number.txt
          echo "New Release Number: $((release_number + 1))"
        #   echo "New Release Number: $((release_number + 1))" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --global user.name "carcas_utility_account"
          git config --global user.email "burkhardth@carleton.edu"

          git add -A
          git commit -m "[automated commit]: update version number"
          git push
